<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block \Zenki\Zenkipay\Block\Onepage\Success
 */
?>

<?php $zenkipay = $block->getPurchaseOptions(); ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Zenki_Zenkipay/js/modal": {
                "zenki_order_id": "<?php echo $zenkipay['zenki_order_id']; ?>",
                "payment_signature": "<?php echo $zenkipay['payment_signature']; ?>"
            }
        }
    }
</script>
