<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block \Zenki\Zenkipay\Block\Onepage\Success
 */
?>

<?php $zenkipay = $block->getTransactionHash(); ?>

<div class="checkout-success">
    <h2>ZENKIPAY DETAILS</h2>
    <p><?php echo __('Transaction hash: '); ?><a href="<?php echo $block->escapeHtml($zenkipay['trx_explorer_url']); ?>" target="_blank"><?php echo $block->escapeHtml($zenkipay['trx_hash']); ?></a></p>
</div>
