<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block \Zenki\Zenkipay\Block\Onepage\Success
 */
?>

<?php $zenkipay = $block->getPurchaseOptions(); ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Zenki_Zenkipay/js/modal": {
                "public_key": "<?php echo $zenkipay['public_key']; ?>",
                "signature": "<?php echo $zenkipay['signature']; ?>",
                "purchase_data": <?php echo $zenkipay['purchase_data']; ?>
            }
        }
    }
</script>
